baseURL = "https://nz.shoogle.net/new-zealand/"
languageCode = "en-US"
title = "New Zealand"
theme = "ln-base"

disableKinds = ["RSS", "robotsTXT"]
enableGitInfo = true

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "new-zealand"

[taxonomies]
  shop = "shops"

